### ISSUE TITLE
Issues with artwork templates

### ISSUE THREAD

**Issue by Gnurou** [pimoroni/picade-hat#26]
I would love to submit a pull request for this since I fixed the templates for my own use, but sadly the repository only contains the PDF.

After printing my own artwork based on the templates, I noticed the two following issues:

1) On the joystick artwork, the leftmost and rightmost screw holes are too low, and too far on the right.

2) On the screen artwork, the indicated top is actually the bottom. The correct template can be obtained by vertically flipping (not rotating, since the left and right borders are not of equal size!) the design.

These errors (especially 1) can easily be verified by printing the templates and layering the original artwork on top. For 2, notice how the taller band is on the top, while it is on the bottom of an assembled Picade.

**Comment by Gadgetoid** [comment]
@sandyjmacdonald I think this has long since been obsoleted by the newer model(s) of Picade and the artwork template since updated, so closing for now.
