### ISSUE TITLE
Gen 1 Picade console input and audio

### ISSUE THREAD

**Issue by Wilstorm** [pimoroni/picade-hat#28]
I don't if this is the correct place to post but I am having an issue with a Picade console input (version 1--the older one). I put together the console, wired it and installed the script.

The joystick and all the buttons work correctly. The older gen console has two buttons on each side and 2 buttons on the front. I've been trying to reassign the button values with commands similar to below in the ```/boot/config.txt```. It doesn't seem to honor the changes and uses the defaults regardless which are similar to MAME defaults ```button 1 = LCTRL```, ```button 2 = LALT```, ```button 3 = SPACE```, ```button 4 = LSHIFT```, ```button 5 = Z ```and ```button 6 = X```. What is different in comparison to MAME is ```credit = C``` and ```player 1 start = A``` vs ```5``` and ```1``` respectively or it would be a perfect setup. :)

I am running a current version of RetroPie on a Pi 3B+ patched current (4.4.11). I am very familiar and comfortable with advanced RetroPie configuration but not quite sure what to do here as I can't seem to find good documentation or videos anywhere. I found some guys video on assembly and kind of patched together inputs from some of the docs here. 

```
dtoverlay=picade
dtparam=up=103
dtparam=down=108
dtparam=left=105
dtparam=right=106
dtparam=button1=42
dtparam=button2=44
dtparam=button3=45
dtparam=button4=29
dtparam=button5=56
dtparam=button6=57
dtparam=enter=28
dtparam=escape=1
dtparam=coin=2
dtparam=start=6
```
Also I have no audio. It auto-added the line ```dtoverlay=audio=off``` to ```/boot/config.txt``` during the script install but when I change it to ```dtoverlay=audio=on``` it boots fine until I launch a game then it locks up. When I switch it back to ```dtoverlay=audio=off``` and I can at least launch a game but with no audio.

Any help with either issue would be greatly appreciated it.

**Comment by Wilstorm** [comment]
@Gadgetoid - I did find a post on the Pimoroni by you with this information which seems to be the ticket for correcting the input.

```
If you need to alter the keyboard keys used by Picade HAT to aid your configuration and avoid clashes with builtin hard-bindings then you can edit the device tree overlay file. It’s easier than it sounds and basically involves finding every instance of linux,code = <n>; in https://github.com/pimoroni/picade-hat/blob/master/picade.dts 6 and replacing it with the keycode you want to use from here - https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h 5.

You can then “make && sudo make install” to build and install the new dtoverlay.
```
When I run the ```make && sudo make install``` I get this:

```
pi@retropie:~/Pimoroni/picade/picade-hat $ make && sudo make install
dtc -I dts -O dtb -o picade.dtbo picade.dts
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@0 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@1 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@2 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@3 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@4 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@5 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@6 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@7 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@8 has a unit name, but no reg property
FATAL ERROR: Couldn't open output file picade.dtbo: Permission denied
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```
When I run ```sudomake && sudo make install```. Basically I just added ```sudo``` to the front of the command. It seems to run but with warnings.

```
pi@retropie:~/Pimoroni/picade/picade-hat $ sudo make && sudo make install
dtc -I dts -O dtb -o picade.dtbo picade.dts
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@0 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@1 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@2 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@3 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@4 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@5 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@6 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@7 has a unit name, but no reg property
picade.dtbo: Warning (unit_address_vs_reg): Node /fragment@8 has a unit name, but no reg property
cp picade.dtbo /boot/overlays/
```

I will test this tonight but still no luck with audio.

**Comment by Wilstorm** [comment]
I tried two methods to modify the default inputs but neither seem to work.

Method 1: Adding the parameters directly to ```/boot/config.txt```. For example dtparam=up=103, dtparam=down=108, etc. using the [linux input keycodes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h). Reboot.

Method 2: Modifying /Pimoroni/picade/picade-hat/picade.dts directly using the [linux input keycodes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h). Then running ```make``` and ```sudo make install```. Reboot.

Neither method seems to change the default input values. Any help would be greatly appreciated as I am at a loss as to what to do. I spent like $75 US plus shipping and right now it's a large paper weight! ;) Thank you.

**Comment by Wilstorm** [comment]
Just to add one more thing. I tried a new RetroPie image (4.4 on stretch--current image as of 04/04/19) and still no luck. I am using the older version 1 picade hat PCB. Is the old hat compatible with the newer RetroPie versions? It seems like it should be with a software tweak.

It does work right out of the box without any software installed so I believe it's fine from an assembly and hardware point of view. 

I suspect the software or script but lack the ability to troubleshoot the issue. I will shelf the Picade console and leave this issue open in hopes of getting a response to help troubleshoot at some point. Cheers.

**Comment by Gadgetoid** [comment]
Really sorry- I seem to have somehow missed this entire issue. Did you ever have any luck getting this to work?

**Comment by Wilstorm** [comment]
@Gadgetoid - Sorry for the slow reply as we had a long holiday weekend and playing catch-up now. No, I wasn't able to tweak the controls or get audio working properly. 

I tried to _thoroughly_ document everything above if the opportunity came around to get it working. It's a nice small light unit that I really would like to utilize. I know the hat isn't defective as the defaults do work but I could never tweak them with the methods stated above. As for audio I never could get it working.

I mainly use RetroPie and have a well established setup with multiple emulators so being able to tweak the inputs was important and of course audio is obvious. :) I am running RetroPie 4.5.1 on a Pi 3 but I believe a new version will be out soon with support for the Pi 4 which I've been patiently waiting for release. 

Any tips or help in getting the unit working would be greatly appreciated!

**Comment by Wilstorm** [comment]
@Gadgetoid - I haven't heard from you in several weeks. Are you still willing to help resolve these few issues? If there's any additional information or testing I may provide I would be more than willing to help get the ball rolling. Cheers.

**Comment by Gadgetoid** [comment]
Sorry- had a mix of being busy, sick, then busy again.

First off. if your Picade board a "HAT" that connects to the Raspberry Pi GPIO pins, or a separate board connected via USB? The software setup for these is quite dramatically different, and the problems you're having seem to point toward it being the latter.

**Comment by Wilstorm** [comment]
@Gadgetoid - It's such a bad time of year to get sick. I wonder if all the business of the holidays and running around preparing for them runs us down just enough to be make us more susceptible. =/

Yes, you're correct it's the older (original?) that connects via USB. I bought it once and never really had a single game session due to configuration/setup. I have a larger heavier homemade unit that's similar that uses an iPAC and works great but this lighter/smaller unit appeals to me for family get together(s) over the holidays. Plus it's more aesthetically pleasing than mine. :)

**Comment by Gadgetoid** [comment]
Ah! The USB connection will surely explain the issues with it- this GitHub repository is only for the GPIO-connected HAT version and none of the software, installers or configuration here will have any (at least not positive) effect on the USB version.

There were a few boards that connected via USB. Just to make things complicated. If youre is an red or blue board - pictured below - then it should be easier to get up and running than the original KickStarter edition.

![image](https://user-images.githubusercontent.com/1746967/70654265-daf88100-1c4d-11ea-9347-1574cadcc402.png)
![image](https://user-images.githubusercontent.com/1746967/70654267-de8c0800-1c4d-11ea-8e0c-a2d10dad0f7a.png)

You should remove `dtoverlay=picade` from your `/boot/config.txt` and ensure audio is enabled with `dtparam=audio=on` for starters. The crashes you mention will be unrelated to the Picade itself since the 3.5mm audio output is only an output.

As for configuring controls, it's a little more complicated. The Picade USB usually ships with a basic firmware that has a pre-baked configuration that you cannot change, but there's an optional advanced firmware with plenty of options which you can find documented (including install instructions to update your PCB) here: https://forums.pimoroni.com/t/new-2-x-configurable-keyboard-gamepad-firmware/1881

**Comment by Wilstorm** [comment]
@Gadgetoid - I'll have to check tonight when I get home. I know it's a red PCB but I'm not completely sure if it's the board shown. If there was only one red version then it has to be the correct one. :) 

I'll take a look at the link for the advanced firmware update and configuration.

Is it alright to continue this discussion here and keep that in mind for future reference or move to the other repository. I really appreciate your help and patience at such a busy time of year.

**Comment by Gadgetoid** [comment]
It's no problem to continue here! As long as it helps you get up and running I'm not going to split hairs about where the thread lives.

**Comment by Wilstorm** [comment]
@Gadgetoid - Ok, I checked last night and I actually have the blue version. I guess the cable that came with the kit is pink-ish colored and all coiled up in front of the board so I was thinking the red version.

1. So when I first installed the software after completing the build I used the command below which is completely wrong and for the "pin" version?

```
curl -sS https://get.pimoroni.com/picadehat | bash
```

2. and I should have been using the command below to download the correct files for the blue board?

```
git clone https://github.com/pimoroni/Picade-Sketch
```

3. With these files I can update the firmware following the steps under ```https://github.com/pimoroni/Picade-Sketch/tree/master/update```?

4. Then change the default values or am I missing some steps for using the old USB boards with RetroPie 4.x and the Pi 3?

5. Then use commands similar to below but with new desired values:

```
import serial
picade = serial.Serial('/dev/ttyACM0',9600,timeout=1.0)
picade.write("a 218 217 216 215 128 130 32 129 122 120 115 99 176 177 250 251 105 111 112")
print(picade.readline().strip())
```

I am not super tech savvy here and could use some guidance if possible. Do I put the above lines in a .py file and run it with ```python filename.py``` or how do I use the commands lines above?

I read through the thread and was curious did you ever resolve the hold for volume up/down?

**Comment by Gadgetoid** [comment]
It's been a long while since I've touched this code, but your step-by-step looks right.

You do- indeed- put those commands into a Python file and run them. You'll also have to make sure you have the `serial` module installed with `sudo pip install pyserial`

I can't even recall the issues with volume so there's a possibility they aren't fixed. It's a slightly odd setup since the amplifier chip requires pulses to turn the volume up/down- makes the code a little bit of a nightmare.

**Comment by Wilstorm** [comment]
@Gadgetoid - Thanks a bunch for all the help and input. I really appreciate it. I'll need a little time to sort through the tables and get everything setup and tested but I'll post back here once completed.

**Comment by Wilstorm** [comment]
@Gadgetoid - In regards to the audio. I tried adding ```dtparam=audio=on``` but that didn't seem to make a difference the audio always prefers the HDMI cable/output to the TV. Then I tried forcing the audio through the 3.5mm audio jack with ```raspi-config``` and that does seem to work.

The drawback is it always uses the speaker. Is there any way to use HDMI when hooked to a TV and the speaker when connected to a monitor? Are you forced to manually switch it? With raspi-config audio settings set to ```auto``` it always uses the HDMI it seems.

**Comment by Gadgetoid** [comment]
Yes, unfortunately you have to manually switch- at least as far as I'm aware. I can't recall if RetroPie has a built-in option for this, but it's a nuisance all the same.

**Comment by Wilstorm** [comment]
@Gadgetoid - Ah ok, well the audio does work well with a little manual intervention. If that was automatic it would be the perfect board. I'll keep digging in RetroPie to see what I may find as I know it very well after using it for years now.

The firmware upgrade was a breeze and using the python script to change values was a snap. Your example script and tables with all the valid values is tremendously helpful. The documentation was superb and well written. I am a firm believer that a product is only as good as it documentation. 5 gold computers out of 5.

By the way I did _not_ need to install the serial module it was downloaded with AVRDUDE when upgrading the firmware. So python and the serial module were already present when scripting new values to the inputs.

I really appreciate you taking the time. Really the only (but primary reason for issues) was being in the wrong repository and loading the wrong software to change the input values on the old blue boards. 

Thank you very much for all the help and guidance it getting things up and running as it would have probably been thrown away in a year or two but now it's a fully functioning unit.

I'll close this out now and best wishes to you and yours for a joyous holiday season! :)
