### ISSUE TITLE
install.sh doesn't add "dtoverlay=gpio_key"

### ISSUE THREAD

**Issue by unwiredben** [pimoroni/picade-hat#32]
I was trying to get the Picade Hat working on an existing RetroPie SD card that I had; after updating everything to latest versions and running the installer, I still wasn't getting buttons to respond.

After some debugging, I found the problem was that the installer was adding dtoverlay=picade to config.txt, but that wouldn't work unless dtoverlay=gpio_key was also in the file.  Adding logic to the script to ensure that line exists may help prevent hair pulling for other users in the future.

**Comment by Gadgetoid** [comment]
This shouldn't be the case- the Picade dtoverlay already includes `gpio_key` setup for each individual key by configuring the `gpio-keys` module.

IE here's the `gpio-key` overlay:

https://github.com/raspberrypi/linux/blob/2fab54c74bf956951e61c6d4fe473995e8d07010/arch/arm/boot/dts/overlays/gpio-key-overlay.dts#L23-L32

And here's what Picade.dtbo does:

https://github.com/pimoroni/picade-hat/blob/df02844c0cd773af5b908f47eac5fb1f7f361531/picade.dts#L41-L128

So adding `gpio_key` should have no effect whatsoever.

I wonder if it could have been a coincidence, or some underlying issue?
