### ISSUE TITLE
Support for Recalbox?

### ISSUE THREAD

**Issue by djibux** [pimoroni/picade-hat#33]
Hello,

Recalbox is a very popular alternative to Retropie.  It’s arguably more user friendly and easier to use.

I would love it if you could provide an install script for Recalbox.

**Comment by djibux** [comment]
One last thing.

Whilst the setup above is very usable, you can't change the in-game key mapping using emulation station.  It only changes the key mapping for the Emulation Station menus.
There is also no key to access the Retroarch menu by default. That's because Recalbox does not officially support keyboards as a game controller.  Theoretically, you can change them using Retroarch menu though, and save it in the core configuration, or create a config file manually and point to that file using the `global.configfile` parameter in `recalbox.conf`.

I chose another solution.

In `recalbox.conf` I added the following lines in the GIPO section:
```
controllers.gpio.enabled=1
controllers.gpio.args=map=5 gpio=12,6,20,16,24,23,9,25,10,11,5,8,27
```
That's the way [Recalbox recommends setting up GPIO controllers](https://github.com/recalbox/recalbox-os/wiki/GPIO-controllers-(EN)).
The good news is that this setup allows you to configure in-game key mapping easily using Emulation Station, including defining a hotkey.
Note that only 13 buttons can be configured that way.  I chose not to configure the button on the left side of the cabinet and keep it mapped to the Esc key.  As a result, you can use it as a convenient shortcut to quit a game.

To avoid conflicts between the Picade overlay and the Recalbox GPIO settings, you need to add the following lines at the bottom of your `/boot/config.txt` file:
```
dtoverlay=picade
dtparam=up=
dtparam=down=
dtparam=left=
dtparam=right=
dtparam=button1=
dtparam=button2=
dtparam=button3=
dtparam=button4=
dtparam=button5=
dtparam=button6=
dtparam=enter=
# dtparam=escape=
dtparam=coin=
dtparam=start=
```

**Comment by Gadgetoid** [comment]
Wow, sorry I hadn't even got around to mentioning that it might be complicated to get up and running on Recalbox, and you've gone and figured it out. This is the best kind of GitHub issue :D

I reckon it would be worth me collating what you've learned into a `recalbox-driver` directory, like the Lakka one: https://github.com/pimoroni/picade-hat/tree/master/lakka-driver

The dts issue is a tricky one since, as far as I know, the output of the dts compiler can change in certain conditions so it's not always wise to ship a pre-compiled file. This may only be across different major releases of the operating systems though.

**Comment by djibux** [comment]
Thanks for the feedback!

Maybe Recalbox could include `dts` in their image.  I know they use buildroot to create a custom system.  I somehow can't post on their forum: every single message I post is rejected by the spam filter :S

For now, I can provide my `dtbo` if you want, as it works with the current version of Recalbox.

**Comment by djibux** [comment]
Recalbox 7 is out and I just did a clean install.
The steps above still work.

**Comment by Magaki99** [comment]
Hello,

I'm interested for working a Recalbox on a Picade.
But I have only a PC with Windows, no any Linux OS.

Could you provide a guide which any user could do it ? I will add to Recalbox Forum.

Thanks in advance.
Kind regards.

**Comment by djibux** [comment]
@Magaki99, here is my dtbo file as well as a basic script I run after each update to update asound.conf and udev rules: [
[picade.zip](https://github.com/pimoroni/picade-hat/files/5761800/picade.zip).  Each update deletes those two files, so I manually launch the script after each update.

To get Recalbox running on your Picade, you need to apply the following steps to your Recalbox SD card:
* Copy the file `picade.dtbo` to `/overlays/` on the BOOT partition of the SD card.
* On the same partition, edit the file `config.txt` and add those lines at the bottom.
```
dtoverlay=picade
dtparam=up=
dtparam=down=
dtparam=left=
dtparam=right=
dtparam=button1=
dtparam=button2=
dtparam=button3=
dtparam=button4=
dtparam=button5=
dtparam=button6=
dtparam=enter=
# dtparam=escape=
dtparam=coin=
dtparam=start=
```
* Copy the file `asound.conf` in the `/etc/` folder of the RECALBOX partition of the SD card.
* Copy the file `10-picade.rules` to the `/etc/udev/rules.d/` folder on the RECALBOX partition of the SD card.
* Adapt section `D2 - GPIO Controllers` of you recalbox.conf so that it reads:
```
controllers.gpio.enabled=1
controllers.gpio.args=map=5 gpio=12,6,20,16,24,23,9,25,10,11,5,8,27
```

All that can be done from a windows computer… Or at least I hope, I can't test here :)

**Comment by yodatak** [comment]
Hi  @djibux  do you already try in batocera linux  ? I'm trying but failling

**Comment by djibux** [comment]
Hello,

I have never tried Batoreca.  I would need to look deeper into this.  I can invest some time if you tell me Batocera is worth it :)  The interface seems pretty.

Recalbox and Batocera both use Buildroot, but Batocera seems to handle overlays a bit differently.

You should probably adapt the `batocera.conf` file to add the GPIO configuration : see https://wiki.batocera.org/kit_to_get_a_batocera?s[]=gpio#gpio_pads

In what state are you?  Is it booting?  Do you have an image?  Do you have sound?  Are the buttons working?

**Comment by mikejolley** [comment]
I got quite far with this on Batoreca, however, the `gpio` idea ([from this comment](https://github.com/pimoroni/picade-hat/issues/33#issuecomment-753637686)) technically worked, but broke audio. I couldn't work out why. Looking for an alternative solution for mapping in retoarch.

**Comment by djibux** [comment]
@mikejolley, you might want to try adapting the `batocera.conf` file adding the GPIO configuration as I mentioned above.

**Comment by mikejolley** [comment]
@djibux Yeah that's where I had to do it. Added to 'batocera.conf' over the network, SSH in and ran 'batocera-save-overlay' then rebooted. This was what I added:

'''
controllers.gpio.args="map=5 gpio=12,6,20,16,24,23,9,25,10,11,5,8,27"
'''

As I said, looked promising and did work in terms of input, but that broke audio as soon as the input device connected. I can only assume the audio also uses GPIO and there was some kind of conflict.

**Comment by djibux** [comment]
OK. Does audio work again if you remove that line?

**Comment by mikejolley** [comment]
@djibux yeah, works fine without a gpio controller, if I leave it as default (keyboard input).

**Comment by djibux** [comment]
It's really strange. I somehow understand how the overlay could cause an issue but not that line in the config file.

**Comment by mikejolley** [comment]
@djibux I know :( spent a lot of time today trying to solve it but no luck. Going to avoid gpio and stick with keyboard control.

It's quite easy to reproduce. I had 2 installs and both did the same thing once I enabled gpio controllers.

**Comment by djibux** [comment]
Hello,

I could get the Picade to work with Recalbox 8.0 with extra tweaking:
- you need to boot once without the Picade hat (or to boot with another raspberry).  It seems there is some kind on initialization process during the first boot that fails when the hat is mounted.
- you need to change the `recalbox.conf` file with the following setting: `global.videomode=auto`
- and you need a few more lines in the `config.txt` file:
```
dtoverlay=hifiberry-dac
force_eeprom_read
```

Game on!

**Comment by RaZer0k** [comment]
Anyone knows how to set shutdown button in recabox... i try setting 
system.power.switch=PIN76PUSH in recalbox.conf
and dtoverlay=gpio-shutdown,gpio_pin=17,active_low=1,gpio_pull=up in config.txt
but nothing happen

**Comment by djibux** [comment]
I did not try that as shutting down with the power menu (select) is easy enough.
If you're using Recalbox 8.0, the `system.power.switch` feature seems broken but should be fixed in 8.1. 🤞

**Comment by Tulbur** [comment]
Hello djibux can you make a tutorial for recalbox 8. nothing works for me

**Comment by djibux** [comment]
Hello,
Have you tried the steps described [here](https://github.com/pimoroni/picade-hat/issues/33#issuecomment-753637686) and [here](https://github.com/pimoroni/picade-hat/issues/33#issuecomment-986381602)?

**Comment by Tulbur** [comment]
Yes I have just redone:

    Copy the file picade.dtbo to /overlays/ on the BOOT partition of the SD card.
    On the same partition, edit the file config.txt and add those lines at the bottom.

dtoverlay=picade
dtparam=up=
dtparam=down=
dtparam=left=
dtparam=right=
dtparam=button1=
dtparam=button2=
dtparam=button3=
dtparam=button4=
dtparam=button5=
dtparam=button6=
dtparam=enter=
# dtparam=escape=
dtparam=coin=
dtparam=start=

    Copy the file asound.conf in the /etc/ folder of the RECALBOX partition of the SD card.
    Copy the file 10-picade.rules to the /etc/udev/rules.d/ folder on the RECALBOX partition of the SD card.
    Adapt section D2 - GPIO Controllers of you recalbox.conf so that it reads:

controllers.gpio.enabled=1
controllers.gpio.args=map=5 gpio=12,6,20,16,24,23,9,25,10,11,5,8,27

And I just have the sound at startup, the image, the joystick is not recognized

**Comment by djibux** [comment]
What happens if you only put `dtoverlay=picade` in the `config.txt`, but not the other lines?

Are you using a Pi 3 or 4?

Le 16 avril 2022 14:10:32 GMT+02:00, Tulbur ***@***.***> a écrit :
>Yes I have just redone:
>
>    Copy the file picade.dtbo to /overlays/ on the BOOT partition of the SD card.
>    On the same partition, edit the file config.txt and add those lines at the bottom.
>
>dtoverlay=picade
>dtparam=up=
>dtparam=down=
>dtparam=left=
>dtparam=right=
>dtparam=button1=
>dtparam=button2=
>dtparam=button3=
>dtparam=button4=
>dtparam=button5=
>dtparam=button6=
>dtparam=enter=
># dtparam=escape=
>dtparam=coin=
>dtparam=start=
>
>    Copy the file asound.conf in the /etc/ folder of the RECALBOX partition of the SD card.
>    Copy the file 10-picade.rules to the /etc/udev/rules.d/ folder on the RECALBOX partition of the SD card.
>    Adapt section D2 - GPIO Controllers of you recalbox.conf so that it reads:
>
>controllers.gpio.enabled=1
>controllers.gpio.args=map=5 gpio=12,6,20,16,24,23,9,25,10,11,5,8,27
>
>And I just have the sound at startup, the image, the joystick is not recognized
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pimoroni/picade-hat/issues/33#issuecomment-1100650258
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
djib

**Comment by Tulbur** [comment]
I use pi 4.
i made a new install,
copy the file picade.dtbo to /overlays/ on the BOOT partition of the SD card  
put `dtoverlay=picade` in the `config.txt

I have image, sound, joystick but no buttons and no input to controller settings.

**Comment by djibux** [comment]
> `edit 10-picade.rules and change ID_INPUT_KEYBOARD by ID_INPUT_JOYSTICK`

Nice!  How did you figure that out?
I'm guessing you have an earlier version of the Picade arcade.  The picade hat used to have two modes but I believe the latest ones don't.  I might be wrong.

**Comment by Tulbur** [comment]
I'm lucky :)
I have picade x hat usb-c, there is a switch button but I do not know what it is for

**Comment by djibux** [comment]
Were you able to map all 10 buttons?  With `controllers.gpio.args`, only 9 can be mapped.

**Comment by Tulbur** [comment]
yes you can map all buttons, it' recognized as gpio keys.
If we activate the GPIO, there is no more sound

**Comment by djibux** [comment]
Oh, you're using Batocera?  I was unable to make it work.  Good work!

**Comment by Tulbur** [comment]
No I do not use it, I wanted to quote a message I made a bad manipulation :) i use retropie, but i can try for batocera

**Comment by yoyojacky** [comment]
Anybody knows how to let recalbox supports dwc2 overlay ?

**Comment by RaZer0k** [comment]
controllers.gpio.enabled=1
controllers.gpio.args=map=5 gpio=12,6,20,16,24,23,9,25,10,5,11,8,27

correct mapping for recalbox (change 5 and 11 (x and y button))
