### ISSUE TITLE
Support for Ubuntu 64 bit on Pi

### ISSUE THREAD

**Issue by solarboogie** [pimoroni/picade-hat#34]
Hi - when using ubuntu 64 bit on a raspberry pi this wont install using the standard script.
You get the message 'hardware not supported'.
Is there any way round this?
I have a Picade based around a Rasberry Pi 4 and would like to run retropie on top of Ubuntu 64 bit as I want to use the Picade for more than just games.

**Comment by Gadgetoid** [comment]
Most of the individual install steps probably work, but we're very far behind the 64bit curve.

As you can see by :scream: the last commits being ~2 years ago :scream: this project needs an overhaul.

It's been... an odd two years.
