### ISSUE TITLE
Question: Which 'license' ?

### ISSUE THREAD

**Issue by ShigeakiAsai** [pimoroni/picade-hat#47]
I have a question.
Which 'license' are [picade-hat](https://github.com/pimoroni/picade-hat) used ?
It had seem to use the MIT license in the past.

Thanks,
ASAI, Shigeaki

**Comment by Gadgetoid** [comment]
The original Python library was, and still is, MIT. All the new stuff is just config files- but you can consider those MIT too, if a license is even meaningful/enforceable on config.

**Comment by ShigeakiAsai** [comment]
Thank you very much for your answer.


ASAI, Shigeaki
